In [22]:
import pandas as pd
from spellchecker import SpellChecker
import re
spell = SpellChecker()
df = pd.read_csv('Downloads/ready_3rd_pass.csv')
df['Processed'] = "NA"
df = df[df['Industry'].notnull()]
for index, row in df.iterrows():

    x = re.findall(r"[\w']+", row['Industry'])
    x = [spell.correction(w.lower()) for w in x]
    df.at[index, 'Processed'] = ' '.join(x)

In [23]:
value_counts = df.Processed.value_counts().to_frame()
df_v = pd.DataFrame(value_counts)
df_v = df_v.reset_index()
df_v.columns = ['Industry', 'count']

In [18]:
text_file = open("Downloads/stopwords.txt", "r")
stopwords = text_file.read().split('\n')


custom_stop = ["agency","animal","autobody","automobile","beverage","bpo","business","call","camp","canadian","car","center","centre","commercial","community","control","course","culture","customer","development","employed","employment","equipment","fire","firm","foods","glass","group","home","house","housing","human","immigration","industry","information","interior","keeping","living","local","long","maintenance","natural","non","none","office","organization","pet","private","processing","production","protection","real","safety","sands","save","sector","self","senior","service","services","social","support","temp","term","tire","trade","trades","trading","various","video","windows","work","worker","works"]

stopwords.extend(custom_stop)

In [72]:
df_new = df_v
df_new = df_new[df_new['Industry'].notnull()]
df_new['Processed'] = 'hello'

df_new['combined'] = False
df_new['new_count']=0
df_new['match'] = "NA"
df_new['association'] = "NA"
print(df_new)
df_new = df_new.sort_values(by = 'count', ascending = False)
top_entries = df_new.iloc[0:300,:]
print(top_entries['count'].sum())
top_entries = list(top_entries.Industry)


                                
print(top_entries)

                       Industry  count Processed  combined  new_count match  \
0                       service    378     hello     False          0    NA
1                            it    289     hello     False          0    NA
2              customer service    279     hello     False          0    NA
3                        trades    263     hello     False          0    NA
4               social services    211     hello     False          0    NA
...                         ...    ...       ...       ...        ...   ...
4857  minute muffler and brakes      1     hello     False          0    NA
4858     andrew pile black hill      1     hello     False          0    NA
4859                     notary      1     hello     False          0    NA
4860                     crafts      1     hello     False          0    NA
4861                aba therapy      1     hello     False          0    NA

     association
0             NA
1             NA
2             NA
3             NA
4             NA
...          ...
4857          NA
4858          NA
4859          NA
4860          NA
4861          NA

[4862 rows x 7 columns]
4177
['service', 'it', 'customer service', 'trades', 'social services', 'production', 'service industry', 'social work', 'housing', 'maintenance', 'trade', 'employment services', 'i a', 'human services', 'services', 'self employed', 'office', 'social service', 'glass', 'call centre', 'immigration', 'commercial', 'automobile', 'community services', 'camp', 'e commerce', 'private', 'restraint', 'business', 'call center', 'academia', 'foods', 'temp agency', 'autonomy', 'flagging', 'eastwood', 'commerce', 'winning', 'save on foods', 'none', 'various', 'employment', 'carpenter', 'canadian tire', 'i i', 'trading', 'a i', 'safety', 're', 'fire protection', 'social', 'fishery', 'brewery', 'car', 'he', 'home', 'scaffolding', 'house keeping', 'community support', 'home support', 'bro', 'fuck', 'superstore', 'custodial', 'customer services', 'biotechnology', 'nursery', 'florist', 'stucco', 'retailer', 'credit union', 'salvation army', 'group home', 'sidelining', 'seniors home', 'meat processing', 'starbucks', 'academic', 'pet', 'landfill', 'seafood', 'jewelry', 'sewing', 'self employment', 'gravel', 'esthetics', 'import export', 'fiberglass', 'no', 'tire', 'poultry', 'laborer', 'pest control', 'car industry', 'plastics', 'homeless shelter', 'biotech', 'snow removal', 'community living', 'fuel', 'personal services', 'science', 'funeral', 'social housing', 'appliances', 'diamond drilling', 'groceries', 'coal', 'lighting', 'junk removal', 'freight', 'mechanic', 'temp work', 'journalism', 'insulation', 'preschool', 'support worker', 'caregiving', 'clinic', 'professional services', 'petro canada', 'value village', 'electricity', 'carnival', 'dollar tree', 'marijuana', 'educational', 'utility', 'it industry', 'freight forwarding', 'winners', 'floral', 'tree service', 'event planning', 'rentals', 'sob', 'electric', 'domestic', 'homemade', 'parking', 'cleaner', 'shipbuilding', 'pizza', 'admin', 'rail', 'janitor', 'taxation', 'corrections', 'cable', 'cinema', 'baker', 'arsonist', 'police', 'yer', 'community centre', 'cabinet making', 'fish', 'religious', 'helicopter', 'temp', 'restauration', 'all', 'automobile industry', 'aircraft', 'firefighting', 'do schenke', 'vehicle', 'surveying', 'foodservice', 'camp work', 'beverage', 'computers', 'shipyard', 'beer', 'audio visual', 'first aid', 'gambling', 'costumer service', 'dollarama', 'rebar', 'architectural', 'hazmat', 'cashier', 'telemarketing', 'video game development', 'city', 'heath', 'hairstylist', 'hairdresser', 'mail', 'human service', 'woodworking', 'band office', 'drilling', 'addiction', 'machinery', 'broadcasting', 'physiotherapy', 'addictions', 'excavating', 'summer camp', 'politics', 'pizza hut', 'receptionist', 'tanning', 'bee clean', 'my donald', 'event industry', 'maritime', 'electronic', 'consumer goods', 'bus', 'ufc', 'private home', 'apex', 'custodian', 'infrastructure', 'community service', 'home services', 'tree nursery', 'web', 'brewing', 'ymca', 'logistic', 'inventory', 'agency', 'canadian forces', 'support services', 'senior living', 'contractor', 'hairstyling', 'event', 'signage', 'fish plant', 'pulpmill', 'arboriculture', 'car wash', 'not sure', 'garbage', 'web development', 'equestrian', 'viniculture', 'detailing', 'real state', 'nonworking', 'educational services', 'religion', 'collections', 'professional', 'pet industry', 'framing', 'whole sale', 'electrician', 'constructions', 'shoppers drug mart', 'religious organization', 'long', 'server', 'treatment center', 'chevron', 'family', 'municipality', 'humanitarian', 'siding', 'video', 'wedding', 'nil', 'private family', 'liqour', 'drycleaning', 'casinos', 'my mikes', 'plants', 'retain', 'biology', 'tree planting', 'bottled water', 'fruit', 'social welfare', 'green house', 'sign', 'pne', 'boston pizza', 'cellular', 'best western', 'home decor', 'ministry of children and family development', 'staffing', 'garden center', 'cruise ship', 'international trade', 'laboratory', 'shopping mall', 'cement', 'chiropractic', 'gravel pit', 'senior home', 'abc', 'movies', 'funeral industry']

In [73]:
n=0
p = df_new.iloc[301:,]
for index, row in p.iterrows():
    
    
    x = row['Industry'].split()
    x = [w for w in x if not w in stopwords]

    for xx in x:
        if row['combined'] == False:
            for tt in top_entries:
                t = tt.split()
                t = [w for w in t if not w in stopwords]

                for z in t:
                    if xx == z:
                        if row['combined'] == False:
                            
                            row['combined'] = True
                            df_new.at[df_new.Industry == tt,'new_count'] = df_new['new_count'][df_new.Industry == tt] + row['count']
                            df_new.at[df_new.Industry == tt,'combined'] = True
                            df_new.at[df_new.Industry == row['Industry'], 'count'] = 0
                            df_new.at[df_new.Industry == row['Industry'], 'match'] = xx
                            df_new.at[df_new.Industry == row['Industry'], 'association'] = tt
                            if n < 40:
                                n = n+1
                                print('we got a match')
                                
                                print(xx)
                                print(row)
                                print(df_new[df_new.Industry == tt])
                                print(row['count'])
                                
print('finished')

we got a match
visual
Industry       visual effects
count                       4
Processed               hello
combined                 True
new_count                   0
match                      NA
association                NA
Name: 363, dtype: object
         Industry  count Processed  combined  new_count match association
158  audio visual      6     hello      True          4    NA          NA
4
we got a match
game
Industry       video game industry
count                            4
Processed                    hello
combined                      True
new_count                        0
match                           NA
association                     NA
Name: 359, dtype: object
                   Industry  count Processed  combined  new_count match  \
157  video game development      6     hello      True          4    NA

    association
157          NA
4
we got a match
cabinet
Industry       cabinet maker
count                      4
Processed              hello
combined                True
new_count                  0
match                     NA
association               NA
Name: 286, dtype: object
           Industry  count Processed  combined  new_count match association
176  cabinet making      6     hello      True          4    NA          NA
4
we got a match
funeral
Industry       funeral home
count                     4
Processed             hello
combined               True
new_count                 0
match                    NA
association              NA
Name: 280, dtype: object
   Industry  count Processed  combined  new_count match association
78  funeral      8     hello      True          4    NA          NA
4
we got a match
tree
Industry       tree services
count                      4
Processed              hello
combined                True
new_count                  0
match                     NA
association               NA
Name: 278, dtype: object
        Industry  count Processed  combined  new_count match association
140  dollar tree      7     hello      True          4    NA          NA
4
we got a match
seniors
Industry       seniors
count                4
Processed        hello
combined          True
new_count            0
match               NA
association         NA
Name: 277, dtype: object
        Industry  count Processed  combined  new_count match association
66  seniors home      9     hello      True          4    NA          NA
4
we got a match
welfare
Industry       animal welfare
count                       4
Processed               hello
combined                 True
new_count                   0
match                      NA
association                NA
Name: 275, dtype: object
           Industry  count Processed  combined  new_count match association
331  social welfare      4     hello      True          4    NA          NA
4
we got a match
funeral
Industry       funeral services
count                         4
Processed                 hello
combined                   True
new_count                     0
match                        NA
association                  NA
Name: 287, dtype: object
   Industry  count Processed  combined  new_count match association
78  funeral      8     hello      True          8    NA          NA
4
we got a match
ministry
Industry       ministry
count                 4
Processed         hello
combined           True
new_count             0
match                NA
association          NA
Name: 312, dtype: object
                                        Industry  count Processed  combined  \
322  ministry of children and family development      4     hello      True

     new_count match association
322          4    NA          NA
4
we got a match
import
Industry       import and export
count                          4
Processed                  hello
combined                    True
new_count                      0
match                         NA
association                   NA
Name: 314, dtype: object
          Industry  count Processed  combined  new_count match association
109  import export      8     hello      True          4    NA          NA
4
we got a match
mart
Industry       wal mart
count                 3
Processed         hello
combined           True
new_count             0
match                NA
association          NA
Name: 511, dtype: object
               Industry  count Processed  combined  new_count match  \
218  shoppers drug mart      5     hello      True          3    NA

    association
218          NA
3
we got a match
consumer
Industry       consumer packaged goods
count                                3
Processed                        hello
combined                          True
new_count                            0
match                               NA
association                         NA
Name: 518, dtype: object
           Industry  count Processed  combined  new_count match association
243  consumer goods      5     hello      True          3    NA          NA
3
we got a match
forces
Industry       canadian armed forces
count                              3
Processed                      hello
combined                        True
new_count                          0
match                             NA
association                       NA
Name: 522, dtype: object
            Industry  count Processed  combined  new_count match association
229  canadian forces      5     hello      True          3    NA          NA
3
we got a match
detailing
Industry       car detailing
count                      3
Processed              hello
combined                True
new_count                  0
match                     NA
association               NA
Name: 484, dtype: object
      Industry  count Processed  combined  new_count match association
210  detailing      5     hello      True          3    NA          NA
3
we got a match
funeral
Industry       funeral service
count                        3
Processed                hello
combined                  True
new_count                    0
match                       NA
association                 NA
Name: 495, dtype: object
   Industry  count Processed  combined  new_count match association
78  funeral      8     hello      True         11    NA          NA
3
we got a match
water
Industry       water works
count                    3
Processed            hello
combined              True
new_count                0
match                   NA
association             NA
Name: 496, dtype: object
          Industry  count Processed  combined  new_count match association
333  bottled water      4     hello      True          3    NA          NA
3
we got a match
water
Industry       water treatment
count                        3
Processed                hello
combined                  True
new_count                    0
match                       NA
association                 NA
Name: 526, dtype: object
          Industry  count Processed  combined  new_count match association
333  bottled water      4     hello      True          6    NA          NA
3
we got a match
goods
Industry       sporting goods
count                       3
Processed               hello
combined                 True
new_count                   0
match                      NA
association                NA
Name: 560, dtype: object
           Industry  count Processed  combined  new_count match association
243  consumer goods      5     hello      True          6    NA          NA
3
we got a match
seafood
Industry       seafood processing
count                           3
Processed                   hello
combined                     True
new_count                       0
match                          NA
association                    NA
Name: 561, dtype: object
    Industry  count Processed  combined  new_count match association
103  seafood      8     hello      True          3    NA          NA
3
we got a match
consumer
Industry       consumer package goods
count                               3
Processed                       hello
combined                         True
new_count                           0
match                              NA
association                        NA
Name: 565, dtype: object
           Industry  count Processed  combined  new_count match association
243  consumer goods      5     hello      True          9    NA          NA
3
we got a match
first
Industry       first nations
count                      3
Processed              hello
combined                True
new_count                  0
match                     NA
association               NA
Name: 530, dtype: object
      Industry  count Processed  combined  new_count match association
171  first aid      6     hello      True          3    NA          NA
3
we got a match
firefighting
Industry       woodland firefighting
count                              3
Processed                      hello
combined                        True
new_count                          0
match                             NA
association                       NA
Name: 533, dtype: object
         Industry  count Processed  combined  new_count match association
189  firefighting      6     hello      True          3    NA          NA
3
we got a match
beer
Industry       craft beer
count                   3
Processed           hello
combined             True
new_count               0
match                  NA
association            NA
Name: 540, dtype: object
    Industry  count Processed  combined  new_count match association
172     beer      6     hello      True          3    NA          NA
3
we got a match
re
Industry       re park
count                3
Processed        hello
combined          True
new_count            0
match               NA
association         NA
Name: 546, dtype: object
   Industry  count Processed  combined  new_count match association
50       re     12     hello      True          3    NA          NA
3
we got a match
garden
Industry       garden centre
count                      3
Processed              hello
combined                True
new_count                  0
match                     NA
association               NA
Name: 549, dtype: object
          Industry  count Processed  combined  new_count match association
350  garden center      4     hello      True          3    NA          NA
3

we got a match
tree
Industry       tree work
count                  3
Processed          hello
combined            True
new_count              0
match                 NA
association           NA
Name: 409, dtype: object
        Industry  count Processed  combined  new_count match association
140  dollar tree      7     hello      True          7    NA          NA
3
we got a match
fish
Industry       fish processing
count                        3
Processed                hello
combined                  True
new_count                    0
match                       NA
association                 NA
Name: 410, dtype: object
    Industry  count Processed  combined  new_count match association
175     fish      6     hello      True          3    NA          NA
3
we got a match
aircraft
Industry       aircraft maintenance
count                             3
Processed                     hello
combined                       True
new_count                         0
match                            NA
association                      NA
Name: 414, dtype: object
     Industry  count Processed  combined  new_count match association
188  aircraft      6     hello      True          3    NA          NA
3
we got a match
children
Industry       children
count                 3
Processed         hello
combined           True
new_count             0
match                NA
association          NA
Name: 427, dtype: object
                                        Industry  count Processed  combined  \
322  ministry of children and family development      4     hello      True

     new_count match association
322          7    NA          NA
3
we got a match
value
Industry       pet value
count                  3
Processed          hello
combined            True
new_count              0
match                 NA
association           NA
Name: 384, dtype: object
          Industry  count Processed  combined  new_count match association
137  value village      7     hello      True          3    NA          NA
3
we got a match
shelter
Industry       shelter
count                3
Processed        hello
combined          True
new_count            0
match               NA
association         NA
Name: 385, dtype: object
            Industry  count Processed  combined  new_count match association
98  homeless shelter      8     hello      True          3    NA          NA
3
we got a match
superstore
Industry       real canadian superstore
count                                 3
Processed                         hello
combined                           True
new_count                             0
match                                NA
association                          NA
Name: 398, dtype: object
      Industry  count Processed  combined  new_count match association
63  superstore     10     hello      True          3    NA          NA
3
we got a match
forces
Industry       armed forces
count                     3
Processed             hello
combined               True
new_count                 0
match                    NA
association              NA
Name: 460, dtype: object
            Industry  count Processed  combined  new_count match association
229  canadian forces      5     hello      True          6    NA          NA
3
we got a match
pizza
Industry       pizza place
count                    3
Processed            hello
combined              True
new_count                0
match                   NA
association             NA
Name: 461, dtype: object
    Industry  count Processed  combined  new_count match association
127    pizza      7     hello      True          3    NA          NA
3
we got a match
canada
Industry       service canada
count                       3
Processed               hello
combined                 True
new_count                   0
match                      NA
association                NA
Name: 463, dtype: object
         Industry  count Processed  combined  new_count match association
136  petro canada      7     hello      True          3    NA          NA
3
we got a match
sob
Industry       sob plant
count                  3
Processed          hello
combined            True
new_count              0
match                 NA
association           NA
Name: 474, dtype: object
    Industry  count Processed  combined  new_count match association
126      sob      7     hello      True          3    NA          NA
3
we got a match
seafood
Industry       seafood industry
count                         3
Processed                 hello
combined                   True
new_count                     0
match                        NA
association                  NA
Name: 443, dtype: object
    Industry  count Processed  combined  new_count match association
103  seafood      8     hello      True          6    NA          NA
3
we got a match
game
Industry       video game
count                   3
Processed           hello
combined             True
new_count               0
match                  NA
association            NA
Name: 432, dtype: object
                   Industry  count Processed  combined  new_count match  \
157  video game development      6     hello      True          7    NA

    association
157          NA
3
we got a match
cruise
Industry       cruise
count               3
Processed       hello
combined         True
new_count           0
match              NA
association        NA
Name: 437, dtype: object
        Industry  count Processed  combined  new_count match association
366  cruise ship      4     hello      True          3    NA          NA
3
we got a match
city
Industry       city of barnaby
count                        3
Processed                hello
combined                  True
new_count                    0
match                       NA
association                 NA
Name: 444, dtype: object
    Industry  count Processed  combined  new_count match association
152     city      6     hello      True          3    NA          NA
3
finished

In [83]:
df_new.to_csv('Downloads/third_pass_industry.csv')

In [68]:
import pandas as pd
from spellchecker import SpellChecker
import re
spell = SpellChecker()
text_file = open("Downloads/stopwords.txt", "r")
stopwords = text_file.read().split('\n')
df = pd.read_csv('Downloads/spell_corrected_industry_counts.csv')
df.columns = ['Industry','count']

custom_stop = ["agency","animal","autobody","automobile","beverage","bpo","business","call","camp","canadian","car","center","centre","commercial","community","control","course","culture","customer","development","employed","employment","equipment","fire","firm","foods","glass","group","home","house","housing","human","immigration","industry","information","interior","keeping","living","local","long","maintenance","natural","non","none","office","organization","pet","private","processing","production","protection","real","safety","sands","save","sector","self","senior","service","services","social","support","temp","term","tire","trade","trades","trading","various","video","windows","work","worker","works"]

stopwords.extend(custom_stop)

df_new = df[df['Industry'].notnull()]
df_new['Processed'] = 'hello'

df_new['combined'] = False


print('a')
for index, row in df_new.iterrows():

    x = re.findall(r"[\w']+", row['Industry'])
    x = [spell.correction(w) for w in x]
    df_new.at[index, 'Processed'] = ' '.join(x)
top_entries = list(df_new.iloc[0:500,0])
print('finihsed')

a
finihsed

In [70]:
df_new['new_count']=0
df_new['match'] = "NA"
df_new['association'] = "NA"
n=0
import warnings
warnings.filterwarnings('ignore')
for index, row in df_new.iloc[501:,].iterrows():
    
    
    x = row['Processed'].split()
    x = [w for w in x if not w in stopwords]

    for xx in x:
        if row['combined'] == False:
            for tt in top_entries:
                t = tt.split()
                t = [w for w in t if not w in stopwords]

                for z in t:
                    if xx == z:
                        if row['combined'] == False:
                            
                            row['combined'] = True
                            df_new['new_count'][df_new.Industry == tt] = df_new['new_count'][df_new.Industry == tt] + row['count']
                            df_new['combined'][df_new.Industry == row['Industry']] = True
                            df_new['count'][df_new.Industry == row['Industry']] = 0
                            df_new['match'][df_new.Industry == row['Industry']] = xx
                            df_new['association'][df_new.Industry == row['Industry']] = tt
                            if n < 40:
                                n = n+1
                                print('we got a match')
                                print(n)
                                print(xx)
                                print(row)
                                print(df_new[df_new.Industry == z])
                                print(row['count'])
                                
print('finished')

we got a match
3
travel
Industry       travel & tourism
count                         8
Processed        travel tourism
combined                   True
new_count                     0
match                        NA
association                  NA
Name: 503, dtype: object
   Industry  count Processed  combined  new_count match association
59   travel     97    travel     False          8    NA          NA
8
we got a match
5
landscape
Industry       landscape maintenance
count                              8
Processed      landscape maintenance
combined                        True
new_count                          0
match                             NA
association                       NA
Name: 505, dtype: object
      Industry  count  Processed  combined  new_count match association
192  landscape     25  landscape     False          8    NA          NA
8
we got a match
8
government
Industry       provincial government
count                              8
Processed      provincial government
combined                        True
new_count                          0
match                             NA
association                       NA
Name: 508, dtype: object
      Industry  count   Processed  combined  new_count match association
47  government    137  government     False          8    NA          NA
8
we got a match
9
fishing
Industry       fishing lodge
count                      8
Processed      fishing lodge
combined                True
new_count                  0
match                     NA
association               NA
Name: 509, dtype: object
   Industry  count Processed  combined  new_count match association
69  fishing     82   fishing     False          8    NA          NA
8
we got a match
11
tourism
Industry       tourism/hospitality
count                            8
Processed      tourism hospitality
combined                      True
new_count                        0
match                           NA
association                     NA
Name: 511, dtype: object
   Industry  count Processed  combined  new_count match association
12  tourism    397   tourism     False          8    NA          NA
8
we got a match
13
construction
Industry       construction/trades
count                            8
Processed      construction trades
combined                      True
new_count                        0
match                           NA
association                     NA
Name: 513, dtype: object
       Industry  count     Processed  combined  new_count match association
0  construction   3008  construction     False          8    NA          NA
8
we got a match
14
television
Industry       television
count                   8
Processed      television
combined             True
new_count               0
match                  NA
association            NA
Name: 514, dtype: object
       Industry  count   Processed  combined  new_count       match  \
514  television      0  television      True          0  television

             association
514  film and television
8
we got a match
19
store
Industry       pet store
count                  8
Processed      pet store
combined            True
new_count              0
match                 NA
association           NA
Name: 519, dtype: object
    Industry  count Processed  combined  new_count match association
324    store     14     store     False          0    NA          NA
8
we got a match
21
dental
Industry       dental office
count                      8
Processed      dental office
combined                True
new_count                  0
match                     NA
association               NA
Name: 521, dtype: object
   Industry  count Processed  combined  new_count match association
71   dental     80    dental     False          8    NA          NA
8
we got a match
22
retail
Industry       outdoor retail
count                       8
Processed      outdoor retail
combined                 True
new_count                   0
match                      NA
association                NA
Name: 522, dtype: object
  Industry  count Processed  combined  new_count match association
1   retail   2154    retail     False          8    NA          NA
8
we got a match
25
public
Industry       public transportation
count                              8
Processed      public transportation
combined                        True
new_count                          0
match                             NA
association                       NA
Name: 525, dtype: object
    Industry  count Processed  combined  new_count match association
856   public      4    public     False          0    NA          NA
8
we got a match
26
health
Industry       natural health
count                       8
Processed      natural health
combined                 True
new_count                   0
match                      NA
association                NA
Name: 526, dtype: object
   Industry  count Processed  combined  new_count match association
13   health    390    health     False          0    NA          NA
8
we got a match
31
wood
Industry       wood industry
count                      8
Processed      wood industry
combined                True
new_count                  0
match                     NA
association               NA
Name: 531, dtype: object
    Industry  count Processed  combined  new_count match association
194     wood     25      wood     False          8    NA          NA
8
we got a match
32
computer
Industry       computer
count                 8
Processed      computer
combined           True
new_count             0
match                NA
association          NA
Name: 532, dtype: object
     Industry  count Processed  combined  new_count     match  \
532  computer      0  computer      True          0  computer

           association
532  computer software
8
we got a match
37
dealership
Industry       dealership
count                   7
Processed      dealership
combined             True
new_count               0
match                  NA
association            NA
Name: 537, dtype: object
       Industry  count   Processed  combined  new_count       match  \
537  dealership      0  dealership      True          0  dealership

        association
537  car dealership
7
finished

In [71]:
df_new.head()
df_new['total'] = df_new['count'] + df_new['new_count']
df_new.to_csv('Downloads/second_pass_at_industry_groupings_w_match_and_association.csv')

In [72]:
df_new['match'].value_counts().to_csv('Downloads/second_industry_matches_count.csv')